# Generated by Django 6.0 on 2025-12-06 14:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
    ]
