# Generated by Django 6.0 on 2025-12-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_skill_icon_remove_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='default.jpg', upload_to='blogs/'),
        ),
    ]
